// Code generated by command: go run asmgen.go -decompose -out ../../tfhe/asm_decompose_amd64.s -stubs ../../tfhe/asm_decompose_stub_amd64.go -pkg=tfhe. DO NOT EDIT.

//go:build amd64 && !purego

package tfhe

//go:noescape
func decomposePolyToUint32AVX2(decomposedOut [][]uint32, p []uint32, base uint32, logBase uint32, logLastBaseQ uint32)

//go:noescape
func decomposePolyToUint64AVX2(decomposedOut [][]uint64, p []uint64, base uint64, logBase uint64, logLastBaseQ uint64)
