// Code generated by command: go run asmgen.go -decompose -out ../../tfhe/asm_decompose_amd64.s -stubs ../../tfhe/asm_decompose_stub_amd64.go -pkg=tfhe. DO NOT EDIT.

//go:build amd64 && !purego

package tfhe

//go:noescape
func decomposePolyAssignUint32AVX2(p []uint32, base uint32, logBase uint32, logLastBaseQ uint32, decomposedOut [][]uint32)

//go:noescape
func decomposePolyAssignUint64AVX2(p []uint64, base uint64, logBase uint64, logLastBaseQ uint64, decomposedOut [][]uint64)
