// Code generated by command: go run asmgen.go -vec -out ../../math/vec/asm_vec_amd64.s -stubs ../../math/vec/asm_vec_stub_amd64.go -pkg=vec. DO NOT EDIT.

//go:build amd64 && !purego

package vec

//go:noescape
func addToUint32AVX2(vOut []uint32, v0 []uint32, v1 []uint32)

//go:noescape
func addToUint64AVX2(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func subToUint32AVX2(vOut []uint32, v0 []uint32, v1 []uint32)

//go:noescape
func subToUint64AVX2(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func scalarMulToUint32AVX2(vOut []uint32, v []uint32, c uint32)

//go:noescape
func scalarMulToUint64AVX2(vOut []uint64, v []uint64, c uint64)

//go:noescape
func scalarMulAddToUint32AVX2(vOut []uint32, v []uint32, c uint32)

//go:noescape
func scalarMulAddToUint64AVX2(vOut []uint64, v []uint64, c uint64)

//go:noescape
func scalarMulSubToUint32AVX2(vOut []uint32, v []uint32, c uint32)

//go:noescape
func scalarMulSubToUint64AVX2(vOut []uint64, v []uint64, c uint64)

//go:noescape
func mulToUint32AVX2(vOut []uint32, v0 []uint32, v1 []uint32)

//go:noescape
func mulToUint64AVX2(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func mulAddToUint32AVX2(vOut []uint32, v0 []uint32, v1 []uint32)

//go:noescape
func mulAddToUint64AVX2(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func mulSubToUint32AVX2(vOut []uint32, v0 []uint32, v1 []uint32)

//go:noescape
func mulSubToUint64AVX2(vOut []uint64, v0 []uint64, v1 []uint64)
