// Code generated by command: go run asmgen.go -fold -out ../../math/poly/asm_fold_amd64.s -stubs ../../math/poly/asm_fold_stub_amd64.go -pkg=poly. DO NOT EDIT.

//go:build amd64 && !purego

package poly

//go:noescape
func foldPolyToUint32AVX2(fpOut []float64, p []uint32)

//go:noescape
func foldPolyToUint64AVX2(fpOut []float64, p []uint64)

//go:noescape
func floatModQInPlaceAVX2(coeffs []float64, q float64, qInv float64)

//go:noescape
func unfoldPolyToUint32AVX2(pOut []uint32, fp []float64)

//go:noescape
func unfoldPolyToUint64AVX2(pOut []uint64, fp []float64)

//go:noescape
func unfoldPolyAddToUint32AVX2(pOut []uint32, fp []float64)

//go:noescape
func unfoldPolyAddToUint64AVX2(pOut []uint64, fp []float64)

//go:noescape
func unfoldPolySubToUint32AVX2(pOut []uint32, fp []float64)

//go:noescape
func unfoldPolySubToUint64AVX2(pOut []uint64, fp []float64)
