// Code generated by command: go run asmgen.go -vec_cmplx -out ../../math/poly/asm_vec_cmplx_amd64.s -stubs ../../math/poly/asm_vec_cmplx_stub_amd64.go -pkg=poly. DO NOT EDIT.

//go:build amd64 && !purego

package poly

//go:noescape
func addCmplxToAVX2(vOut []float64, v0 []float64, v1 []float64)

//go:noescape
func subCmplxToAVX2(vOut []float64, v0 []float64, v1 []float64)

//go:noescape
func negCmplxToAVX2(vOut []float64, v []float64)

//go:noescape
func floatMulCmplxToAVX2(vOut []float64, v []float64, c float64)

//go:noescape
func floatMulAddCmplxToAVX2(vOut []float64, v []float64, c float64)

//go:noescape
func floatMulSubCmplxToAVX2(vOut []float64, v []float64, c float64)

//go:noescape
func cmplxMulCmplxToAVX2(vOut []float64, v []float64, c complex128)

//go:noescape
func cmplxMulAddCmplxToAVX2(vOut []float64, v []float64, c complex128)

//go:noescape
func cmplxMulSubCmplxToAVX2(vOut []float64, v []float64, c complex128)

//go:noescape
func mulCmplxToAVX2(vOut []float64, v0 []float64, v1 []float64)

//go:noescape
func mulAddCmplxToAVX2(vOut []float64, v0 []float64, v1 []float64)

//go:noescape
func mulSubCmplxToAVX2(vOut []float64, v0 []float64, v1 []float64)
