//go:build amd64

// Code generated by command: go run main.go -out asm/asm.s. DO NOT EDIT.

#include "textflag.h"

// func fftInPlaceAVX2(coeffs []complex128, wNj []complex128)
// Requires: AVX, FMA3
TEXT ·fftInPlaceAVX2(SB), NOSPLIT, $0-48
	MOVQ coeffs_base+0(FP), AX
	MOVQ wNj_base+24(FP), CX
	MOVQ coeffs_len+8(FP), DX
	MOVQ DX, BX
	SHRQ $0x01, BX

	// t := N / 2
	MOVQ DX, SI

	// for m := 1; m < N/2; m <<= 1
	MOVQ $0x00000001, DI
	JMP  m_loop_end

m_loop:
	// for i := 0; i < m; i++
	XORQ R8, R8
	JMP  i_loop_end

i_loop:
	// Move wNj by one index
	ADDQ $0x10, CX

	// Precompute wNj[m+i]
	VBROADCASTF128 (CX), Y0
	VSHUFPD        $0x05, Y0, Y0, Y1

	// j1 := i * t << 1
	MOVQ  R8, R9
	IMULQ SI, R9
	SHLQ  $0x01, R9

	// j2 := j1 + t
	MOVQ R9, R10
	ADDQ SI, R10

	// We increment j by 4 every iteration
	// for j := j1; j < j2; j++
	JMP j_loop_end

j_loop:
	// U := coeffs[j]
	VMOVUPD (AX)(R9*8), Y2

	// V := coeffs[j+t]
	MOVQ    R9, R11
	ADDQ    SI, R11
	VMOVUPD (AX)(R11*8), Y3

	// V *= wNj[m+i]
	VSHUFPD        $0x0f, Y3, Y3, Y4
	VSHUFPD        $0x00, Y3, Y3, Y3
	VMULPD         Y4, Y1, Y4
	VFMADDSUB231PD Y3, Y0, Y4

	// coeffs[j] = U + V
	VADDPD  Y2, Y4, Y3
	VMOVUPD Y3, (AX)(R9*8)

	// coeffs[j+t] = U - V
	VSUBPD  Y4, Y2, Y3
	VMOVUPD Y3, (AX)(R11*8)

	// j += 4
	ADDQ $0x04, R9

	// j < j2
j_loop_end:
	CMPQ R9, R10
	JL   j_loop

	// i++
	INCQ R8

	// i < m
i_loop_end:
	CMPQ R8, DI
	JL   i_loop

	// t >>= 1
	SHRQ $0x01, SI

	// m <<= 1
	SHLQ $0x01, DI

	// m < N/2
m_loop_end:
	CMPQ DI, BX
	JL   m_loop

	// Last Loop
	// Double N
	ADDQ DX, DX

	// for j := 0; j < N; j += 2
	XORQ R9, R9
	JMP  last_loop_end

last_loop:
	// Move wNj by one index
	ADDQ $0x10, CX

	// Precompute wNj[m+i]
	VMOVUPD (CX), X0
	VSHUFPD $0x01, X0, X0, X1

	// U := coeffs[j]
	VMOVUPD (AX)(R9*8), X2

	// V := coeffs[j+1]
	VMOVUPD 16(AX)(R9*8), X3

	// V *= wNj[m+i]
	VSHUFPD        $0x03, X3, X3, X4
	VSHUFPD        $0x00, X3, X3, X3
	VMULPD         X4, X1, X1
	VFMADDSUB231PD X3, X0, X1

	// coeffs[j] = U + V
	VADDPD  X2, X1, X0
	VMOVUPD X0, (AX)(R9*8)

	// coeffs[j+1] = U - V
	VSUBPD  X1, X2, X0
	VMOVUPD X0, 16(AX)(R9*8)

	// j += 2
	ADDQ $0x04, R9

	// j < N
last_loop_end:
	CMPQ R9, DX
	JL   last_loop
	RET
