name: CI Tests
on:
  push:

jobs:
  tests:
    name: Run Go ${{ matrix.go }} Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18', '1.19', '1.20', '1.21' ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Run Tests
        run: |
          go test ./math/poly -timeout=0
          go test ./tfhe ./tfheb -timeout=0
          go test ./tfhe ./tfheb -timeout=0 -tags=purego
